"""add user_id conv_id to task_runs

Revision ID: 5fa8be9c23ff
Revises: 5adbaccf42d5
Create Date: 2026-08-18 11:39:27.630155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa8be9c23ff'
down_revision: Union[str, None] = '5adbaccf42d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_runs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('task_runs', sa.Column('conv_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_runs_conv_id'), 'task_runs', ['conv_id'], unique=False)
    op.create_index(op.f('ix_task_runs_user_id'), 'task_runs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'task_runs', 'conversations', ['conv_id'], ['id'])
    op.create_foreign_key(None, 'task_runs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_runs', type_='foreignkey')
    op.drop_constraint(None, 'task_runs', type_='foreignkey')
    op.drop_index(op.f('ix_task_runs_user_id'), table_name='task_runs')
    op.drop_index(op.f('ix_task_runs_conv_id'), table_name='task_runs')
    op.drop_column('task_runs', 'conv_id')
    op.drop_column('task_runs', 'user_id')
    # ### end Alembic commands ###
